### ISSUE TITLE
Move Color Formatting From JS

### ISSUE THREAD

**Issue by ewilliams0305** [ewilliams0305/WebLogger#15]
Currently the serilog sink colors are being formatted from the JS file with parsing.  Sinnce sending HTML data to the WebLogger UI works this should be moved to the Serilog Sink.

**Comment by Abraham12611** [comment]
Hello 👋
I'm new to open source. I would love to help and think I would be able to. So, please how do I contribute?

**Comment by ewilliams0305** [comment]
You should be able to fork the repo. Once forked and updated commit your changes and make a pull request back to the Dev branch. I'll review the updates and give it a test. @Abraham12611 thanks, and let me know if your don't have required permissions. FWIW I'm also pretty new at all this, this might help

https://opensource.com/article/19/7/create-pull-request-github

**Comment by Abraham12611** [comment]
Okay, I would start working on it now and make a pull request.
Thanks
